FROM brimstone/kali:latest

RUN apt update \
 && apt install -y --no-install-recommends \
	mitmproxy sqlmap nikto beef-xss bettercap ffuf \
 && apt clean \
 && rm -rf /var/lib/apt/lists

RUN curl https://github.com/brimstone/gobuster/releases/download/1.3-opt/gobuster \
    -Lo /usr/bin/gobuster \
 && chmod 755 /usr/bin/gobuster

# TODO /usr/share/beef-xss /usr/share/beef-xss/beef
