FROM brimstone/kali:latest

RUN apt update \
 && apt install -y --no-install-recommends \
	john hashcat cpio hydra \
    ocl-icd-libopencl1 opencl-headers clinfo \
    python3-pip \
 && apt clean \
 && rm -rf /var/lib/apt/lists

RUN pip install name-that-hash

# https://software.intel.com/content/www/us/en/develop/articles/opencl-drivers.html
#RUN wget -O opencl.tgz https://ipfs.io/ipfs/QmeMxXaWYTS88pfJfsB4FPrkB4WAWQip2C8Ke55NMaTvbx \
# && tar -xvf opencl.tgz \
# && rm opencl.tgz \
# && cd l_opencl* \
# && sed -i 's/=decline/=accept/' silent.cfg \
# && ./install.sh -s silent.cfg \
# && [ -e /etc/alternatives/opencl-libOpenCL.so ] \
# && cd .. \
# && rm -rf l_opencl*
