#!/bin/bash
set -ueo pipefail

# stolen from https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1
             # --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
docker build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --pull -t brimstone/kali:latest .

docker push brimstone/kali:latest

for f in Dockerfile.*; do
	v="${f##Dockerfile.}"
	docker build --pull -f "$f" \
			-t "brimstone/kali:$v" \
			.
done
wait
